// ============================================================
// INNER LIGHT — FIRESTORE SEED DATA
// ============================================================
// This file contains all static content for the app:
//   - Meditation sessions
//   - Sleep stories
//   - Motivational quotes
//
// Run this ONCE using: node scripts/runSeed.js
// ============================================================

export const meditationsData = [
  // ---- FOCUS ----
  {
    title: 'Morning Focus Boost',
    description: 'Start your day with clarity and intention. This session sharpens your mind and prepares you for deep focus.',
    category: 'focus',
    duration: 10,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_8892db8ca2.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    tags: ['morning', 'focus', 'productivity'],
    isPremium: false,
  },
  {
    title: 'Deep Work Preparation',
    description: 'Clear mental clutter and enter a state of deep concentration with this guided focus meditation.',
    category: 'focus',
    duration: 15,
    difficulty: 'intermediate',
    instructor: 'Inner Light',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/25/audio_946ef970a0.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1543966888-7c1dc482a810?w=400',
    tags: ['focus', 'work', 'concentration'],
    isPremium: false,
  },
  {
    title: 'Study Session Centering',
    description: 'Prepare your mind for effective studying with this short centering meditation.',
    category: 'focus',
    duration: 5,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=400',
    tags: ['focus', 'study', 'short'],
    isPremium: false,
  },

  // ---- STRESS & ANXIETY ----
  {
    title: 'Anxiety Relief',
    description: 'Gently release tension and anxiety with calming breath work and body awareness techniques.',
    category: 'anxiety',
    duration: 12,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/11/01/audio_cb756dd941.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=400',
    tags: ['anxiety', 'calm', 'breathing'],
    isPremium: false,
  },
  {
    title: 'Stress Melt Away',
    description: 'A progressive relaxation session designed to dissolve stress from head to toe.',
    category: 'stress',
    duration: 20,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    tags: ['stress', 'relax', 'body-scan'],
    isPremium: false,
  },
  {
    title: 'Panic Relief Breathing',
    description: 'A quick 5-minute session using box breathing to calm a racing mind instantly.',
    category: 'anxiety',
    duration: 5,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    tags: ['anxiety', 'breathing', 'quick'],
    isPremium: false,
  },

  // ---- SLEEP ----
  {
    title: 'Sleep Preparation',
    description: 'Wind down your mind and body with this gentle pre-sleep meditation. Perfect before bed.',
    category: 'sleep',
    duration: 15,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=400',
    tags: ['sleep', 'night', 'wind-down'],
    isPremium: false,
  },
  {
    title: 'Deep Sleep Journey',
    description: 'A longer body-scan meditation to guide you into deep, restorative sleep.',
    category: 'sleep',
    duration: 30,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0c6ff1bbd.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1531353826977-0941b4779a1c?w=400',
    tags: ['sleep', 'deep', 'relaxation'],
    isPremium: false,
  },
  {
    title: 'Let Go of the Day',
    description: 'Release the mental load of the day and transition into peaceful rest.',
    category: 'sleep',
    duration: 10,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?w=400',
    tags: ['sleep', 'release', 'evening'],
    isPremium: false,
  },

  // ---- MORNING ----
  {
    title: 'Sunrise Awakening',
    description: 'Greet the new day with gratitude and positive intention. A gentle way to begin your morning.',
    category: 'morning',
    duration: 8,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400',
    tags: ['morning', 'gratitude', 'intentions'],
    isPremium: false,
  },
  {
    title: 'Morning Energy Activation',
    description: 'Wake up your body and mind with this energizing morning meditation and breath work.',
    category: 'morning',
    duration: 10,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=400',
    tags: ['morning', 'energy', 'breathwork'],
    isPremium: false,
  },

  // ---- MINDFULNESS ----
  {
    title: 'Present Moment Awareness',
    description: 'Anchor yourself in the present moment with this classic mindfulness meditation.',
    category: 'mindfulness',
    duration: 10,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1474418397713-003ec9f03143?w=400',
    tags: ['mindfulness', 'awareness', 'present'],
    isPremium: false,
  },
  {
    title: 'Loving Kindness',
    description: 'Cultivate compassion for yourself and others through this heart-opening meditation.',
    category: 'mindfulness',
    duration: 15,
    difficulty: 'intermediate',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    tags: ['mindfulness', 'compassion', 'kindness'],
    isPremium: false,
  },
  {
    title: 'Body Scan Awareness',
    description: 'Travel through your entire body with awareness, releasing tension along the way.',
    category: 'mindfulness',
    duration: 20,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1494232410401-ad00d5433cfa?w=400',
    tags: ['mindfulness', 'body-scan', 'tension'],
    isPremium: false,
  },

  // ---- BREATHING ----
  {
    title: '4-7-8 Breathing',
    description: 'The 4-7-8 breath is one of the most powerful tools for calming the nervous system.',
    category: 'breathing',
    duration: 5,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1559825481-12a05cc00344?w=400',
    tags: ['breathing', 'nervous-system', 'quick'],
    isPremium: false,
  },
  {
    title: 'Box Breathing',
    description: 'Used by Navy SEALs to stay calm under pressure. 4 counts in, hold, out, hold.',
    category: 'breathing',
    duration: 7,
    difficulty: 'beginner',
    instructor: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    tags: ['breathing', 'box', 'calm'],
    isPremium: false,
  },
];

// ============================================================
// SLEEP STORIES DATA
// ============================================================
export const sleepStoriesData = [
  {
    title: 'The Enchanted Forest',
    description: 'Walk through a magical forest filled with glowing trees and gentle creatures. A peaceful journey to drift you off to sleep.',
    duration: 20,
    narrator: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=400',
    category: 'nature',
    tags: ['forest', 'magical', 'nature'],
    isPremium: false,
  },
  {
    title: 'Ocean Voyage',
    description: 'Set sail on a calm night sea under a blanket of stars. Feel the gentle rocking of the boat and let go.',
    duration: 25,
    narrator: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=400',
    category: 'nature',
    tags: ['ocean', 'night', 'stars'],
    isPremium: false,
  },
  {
    title: 'Mountain Cabin',
    description: 'Rest by a warm fire in a cozy mountain cabin as snow falls softly outside the window.',
    duration: 18,
    narrator: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1518732714860-b62714ce0c59?w=400',
    category: 'cozy',
    tags: ['cabin', 'snow', 'fire', 'cozy'],
    isPremium: false,
  },
  {
    title: 'Desert Stargazing',
    description: 'Lie under an infinite desert sky and watch as shooting stars arc across the universe.',
    duration: 22,
    narrator: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400',
    category: 'nature',
    tags: ['desert', 'stars', 'night'],
    isPremium: false,
  },
  {
    title: 'The Zen Garden',
    description: 'Wander through a traditional Japanese garden, raking patterns in sand and finding perfect stillness.',
    duration: 15,
    narrator: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400',
    category: 'peaceful',
    tags: ['zen', 'garden', 'peaceful'],
    isPremium: false,
  },
  {
    title: 'Rainy Afternoon',
    description: 'Curl up with a warm blanket and a book while rain taps softly on the window.',
    duration: 20,
    narrator: 'Inner Light',
    audioUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1501691223387-dd0500403074?w=400',
    category: 'cozy',
    tags: ['rain', 'cozy', 'reading'],
    isPremium: false,
  },
];

// ============================================================
// MOTIVATIONAL QUOTES DATA
// ============================================================
export const quotesData = [
  { text: 'The present moment is the only moment available to us, and it is the door to all moments.', author: 'Thich Nhat Hanh', category: 'mindfulness' },
  { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius', category: 'strength' },
  { text: 'Breathing in, I calm body and mind. Breathing out, I smile.', author: 'Thich Nhat Hanh', category: 'breathing' },
  { text: 'The mind is everything. What you think, you become.', author: 'Buddha', category: 'mindset' },
  { text: 'Peace comes from within. Do not seek it without.', author: 'Buddha', category: 'peace' },
  { text: 'Almost everything will work again if you unplug it for a few minutes, including you.', author: 'Anne Lamott', category: 'rest' },
  { text: 'You cannot always control what goes on outside. But you can always control what goes on inside.', author: 'Wayne Dyer', category: 'mindset' },
  { text: 'Within you, there is a stillness and a sanctuary to which you can retreat at any time.', author: 'Hermann Hesse', category: 'peace' },
  { text: 'Meditation is not a way of making your mind quiet. It is a way of entering into the quiet that is already there.', author: 'Deepak Chopra', category: 'meditation' },
  { text: 'The quieter you become, the more you are able to hear.', author: 'Rumi', category: 'mindfulness' },
  { text: 'Take rest; a field that has rested gives a bountiful crop.', author: 'Ovid', category: 'rest' },
  { text: 'You are enough. You have enough. You do enough.', author: 'Unknown', category: 'self-love' },
  { text: 'To the mind that is still, the whole universe surrenders.', author: 'Lao Tzu', category: 'peace' },
  { text: 'Nothing can harm you as much as your own thoughts unguarded.', author: 'Buddha', category: 'mindset' },
  { text: 'Your calm mind is the ultimate weapon against your challenges.', author: 'Bryant McGill', category: 'strength' },
  { text: 'Be gentle with yourself. You are a child of the universe.', author: 'Max Ehrmann', category: 'self-love' },
  { text: 'Wherever you are, be all there.', author: 'Jim Elliot', category: 'mindfulness' },
  { text: 'Inhale the future. Exhale the past.', author: 'Unknown', category: 'breathing' },
  { text: 'Happiness is not something ready-made. It comes from your own actions.', author: 'Dalai Lama', category: 'happiness' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb', category: 'action' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson', category: 'strength' },
  { text: 'Each morning we are born again. What we do today matters most.', author: 'Buddha', category: 'morning' },
  { text: 'Slow down and everything you are chasing will come around and catch you.', author: 'John De Paola', category: 'rest' },
  { text: 'Not all those who wander are lost.', author: 'J.R.R. Tolkien', category: 'journey' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein', category: 'strength' },
  { text: 'Stars can\'t shine without darkness.', author: 'Unknown', category: 'hope' },
  { text: 'You don\'t have to be perfect to be amazing.', author: 'Unknown', category: 'self-love' },
  { text: 'One day or day one. You decide.', author: 'Unknown', category: 'action' },
  { text: 'Train your mind to see the good in every situation.', author: 'Unknown', category: 'mindset' },
  { text: 'The soul always knows what to do to heal itself. The challenge is to silence the mind.', author: 'Caroline Myss', category: 'healing' },
];